"""PA4: rigid ICP registration of the probed points to the bone surface.

For each sample k the pointer tip d_k is found in body B coordinates, then ICP
(cisreg.icp) estimates F_reg starting from F_reg = I, using the bounding-box
tree for the matching step. The output lists s_k = F_reg d_k, the closest
point c_k and |s_k - c_k|. A per-iteration residual log is written for each
set, and with --all a summary table of every run.

Usage:
    python -m cisreg.pa4 --set A-Debug
    python -m cisreg.pa4 --all

Author: Parmida Mazloomi
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from cisreg import datasets
from cisreg.boxtree import BoundingBoxTree
from cisreg.cli import build_parser, selected_labels
from cisreg.datasets import ProblemInputs
from cisreg.fileio import write_output
from cisreg.frames import rotation_angle, rotation_vector
from cisreg.icp import IcpOptions, IcpResult, format_history, icp
from cisreg.plots import plot_icp_convergence
from cisreg.search import BruteForceSearch
from cisreg.tracking import pointer_tips


@dataclass(frozen=True)
class Pa4Run:
    label: str
    d: np.ndarray
    result: IcpResult


def solve_pa4(inputs: ProblemInputs, options: IcpOptions | None = None, brute_force: bool = False) -> tuple[np.ndarray, IcpResult]:
    """Pointer tips d_k and the ICP result for one set."""
    search = BruteForceSearch(inputs.mesh) if brute_force else BoundingBoxTree(inputs.mesh)
    d = pointer_tips(inputs.body_a, inputs.body_b, inputs.samples)
    return d, icp(d, search, options=options)


def run_set(data_dir: Path, output_dir: Path, label: str, options: IcpOptions | None = None) -> Pa4Run:
    d, result = solve_pa4(datasets.load_inputs(data_dir, "PA4", label), options)
    write_output(Path(output_dir) / f"PA4-{label}-Output.txt", result.s, result.matches.points)
    return Pa4Run(label, d, result)


def frame_text(R: np.ndarray, p: np.ndarray) -> str:
    alpha = rotation_vector(R)
    return (
        f"{np.degrees(rotation_angle(R)):.4f} | "
        f"[{alpha[0]:.6f}, {alpha[1]:.6f}, {alpha[2]:.6f}] | [{p[0]:.3f}, {p[1]:.3f}, {p[2]:.3f}]"
    )


def summary_markdown(runs: list[Pa4Run], assignment: str = "PA4") -> str:
    lines = [
        f"# {assignment} runs",
        "",
        f"Generated by `python -m cisreg.{assignment.lower()} --all`. Residuals are |s_k - c_k| over all",
        "samples after the last iteration, in mm. F_reg is given as its rotation angle, its rotation",
        "vector (axis times angle, radians) and its translation p (mm).",
        "",
        "| Set | N | Iterations | Stopped because | Mean | RMS | Max | Angle (deg) | Rotation vector | p |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for run in runs:
        r, last = run.result, run.result.history[-1]
        lines.append(
            f"| {run.label} | {len(run.d)} | {r.iterations} | {r.reason} | {last.mean_residual:.4f} "
            f"| {last.rms_residual:.4f} | {last.max_residual:.4f} | {frame_text(r.F.R, r.F.p)} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> None:
    parser = build_parser("PA4", "PA4: rigid ICP registration of probed points to the bone surface.")
    parser.add_argument("--no-outlier-rejection", action="store_true", help="use every pair in every iteration")
    parser.add_argument("--log-dir", type=Path, default=Path("results/logs"), help="per-iteration logs")
    parser.add_argument("--summary", type=Path, default=Path("results/pa4_runs.md"), help="summary table (with --all)")
    parser.add_argument("--figure", type=Path, default=Path("figures/pa4_convergence.png"), help="convergence plot (with --all)")
    args = parser.parse_args(argv)
    options = IcpOptions(reject_outliers=not args.no_outlier_rejection)
    runs = []
    for label in selected_labels(args, "PA4"):
        run = run_set(args.data_dir, args.output_dir, label, options)
        runs.append(run)
        args.log_dir.mkdir(parents=True, exist_ok=True)
        log = args.log_dir / f"PA4-{label}-icp.txt"
        log.write_text(f"PA4-{label}: {run.result.reason}\n" + format_history(run.result.history) + "\n")
        last = run.result.history[-1]
        print(f"PA4-{label}: {run.result.iterations} iterations, RMS {last.rms_residual:.4f} mm")
    if args.all:
        args.summary.parent.mkdir(parents=True, exist_ok=True)
        args.summary.write_text(summary_markdown(runs))
        histories = {run.label: run.result.history for run in runs}
        plot_icp_convergence(histories, args.figure, "PA4: rigid ICP from F_reg = I")


if __name__ == "__main__":
    main()
