"""PA5: deformable registration of the probed points to the statistical shape model.

For each sample k the pointer tip d_k is found in body B coordinates, then
cisreg.deformable estimates F_reg and the mode weights lambda_1 ... lambda_M
(M from the sample file header). The output's first data line holds the
weights; each following line has s_k = F_reg d_k, the closest point c_k on the
deformed surface and |s_k - c_k|.

Usage:
    python -m cisreg.pa5 --set A-Debug
    python -m cisreg.pa5 --all

Author: Parmida Mazloomi
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from cisreg import datasets
from cisreg.cli import build_parser, selected_labels
from cisreg.datasets import ProblemInputs
from cisreg.deformable import DeformableOptions, DeformableResult, deformable_registration, format_deformable_history
from cisreg.fileio import read_modes, write_output
from cisreg.pa4 import frame_text
from cisreg.plots import plot_deformable_convergence
from cisreg.shape_model import ShapeModel
from cisreg.tracking import pointer_tips


@dataclass(frozen=True)
class Pa5Run:
    label: str
    d: np.ndarray
    result: DeformableResult


def solve_pa5(
    inputs: ProblemInputs, atlas: np.ndarray, options: DeformableOptions | None = None
) -> tuple[np.ndarray, DeformableResult]:
    """Pointer tips d_k and the deformable registration result for one set."""
    model = ShapeModel.from_atlas(atlas, inputs.mesh, inputs.samples.n_modes)
    d = pointer_tips(inputs.body_a, inputs.body_b, inputs.samples)
    return d, deformable_registration(d, model, options)


def run_set(data_dir: Path, output_dir: Path, label: str, atlas: np.ndarray, options=None) -> Pa5Run:
    d, result = solve_pa5(datasets.load_inputs(data_dir, "PA5", label), atlas, options)
    write_output(Path(output_dir) / f"PA5-{label}-Output.txt", result.s, result.matches.points, result.weights)
    return Pa5Run(label, d, result)


def summary_markdown(runs: list[Pa5Run]) -> str:
    lines = [
        "# PA5 runs",
        "",
        "Generated by `python -m cisreg.pa5 --all`. Step counts are rigid ICP iterations, mode-weight",
        "steps and combined steps. Residuals are |s_k - c_k| on the final deformed surface, in mm.",
        "",
        "| Set | N | Rigid | Mode | Combined | Converged | Mean | RMS | Max |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for run in runs:
        r, last = run.result, run.result.history[-1]
        lines.append(
            f"| {run.label} | {len(run.d)} | {r.count('rigid')} | {r.count('mode')} | {r.count('combined')} "
            f"| {'yes' if r.converged else 'no'} | {last.mean_residual:.4f} | {last.rms_residual:.4f} "
            f"| {last.max_residual:.4f} |"
        )
    lines += [
        "",
        "Mode weights:",
        "",
        "| Set | " + " | ".join(f"lambda_{m + 1}" for m in range(len(runs[0].result.weights))) + " |",
        "|---|" + "---|" * len(runs[0].result.weights),
    ]
    for run in runs:
        lines.append(f"| {run.label} | " + " | ".join(f"{w:.4f}" for w in run.result.weights) + " |")
    lines += [
        "",
        "F_reg (rotation angle in degrees, rotation vector in radians, translation in mm):",
        "",
        "| Set | Angle (deg) | Rotation vector | p |",
        "|---|---|---|---|",
    ]
    for run in runs:
        lines.append(f"| {run.label} | {frame_text(run.result.F.R, run.result.F.p)} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> None:
    parser = build_parser("PA5", "PA5: deformable registration to the statistical shape model.")
    parser.add_argument("--log-dir", type=Path, default=Path("results/logs"), help="per-step logs")
    parser.add_argument("--summary", type=Path, default=Path("results/pa5_runs.md"), help="summary table (with --all)")
    parser.add_argument("--figure", type=Path, default=Path("figures/pa5_convergence.png"), help="convergence plot (with --all)")
    args = parser.parse_args(argv)
    atlas = read_modes(datasets.modes_path(args.data_dir))
    runs = []
    for label in selected_labels(args, "PA5"):
        run = run_set(args.data_dir, args.output_dir, label, atlas)
        runs.append(run)
        args.log_dir.mkdir(parents=True, exist_ok=True)
        status = "converged" if run.result.converged else "did not converge"
        log = args.log_dir / f"PA5-{label}-deformable.txt"
        log.write_text(f"PA5-{label}: {status}\n" + format_deformable_history(run.result.history) + "\n")
        r = run.result
        print(
            f"PA5-{label}: rigid {r.count('rigid')}, mode {r.count('mode')}, combined {r.count('combined')}, "
            f"RMS {r.history[-1].rms_residual:.4f} mm"
        )
    if args.all:
        args.summary.parent.mkdir(parents=True, exist_ok=True)
        args.summary.write_text(summary_markdown(runs))
        plot_deformable_convergence({run.label: run.result.history for run in runs}, args.figure)


if __name__ == "__main__":
    main()
